#!/usr/bin/env python3
"""Render the GridPix icon art: Play Store icon (512x512), feature graphic (1024x500) and the
adaptive launcher foreground vector (res/drawable/ic_launcher_foreground.xml).

Usage: python tools/store_graphics.py <output-dir-for-pngs>
Needs Pillow (pip install pillow).

Design: a 7x7 pixel mosaic spelling "G" in a violet -> pink -> orange -> gold diagonal gradient,
with the unfilled cells as faint tiles, on a deep night-violet background. Same art everywhere.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

G = [
    ".#####.",
    "##...##",
    "##.....",
    "##.####",
    "##...##",
    "##...##",
    ".#####.",
]
BG = (27, 21, 48)  # #1B1530
STOPS = [(0x7B, 0x5C, 0xFF), (0xC0, 0x5C, 0xF0), (0xFF, 0x4F, 0x8B), (0xFF, 0x8A, 0x3D), (0xFF, 0xC9, 0x3D)]
FAINT = (255, 255, 255, 26)
HERE = os.path.dirname(os.path.abspath(__file__))
VECTOR_OUT = os.path.join(HERE, "..", "app", "src", "main", "res", "drawable", "ic_launcher_foreground.xml")


def grad(t):
    t = max(0.0, min(1.0, t)) * (len(STOPS) - 1)
    i = min(int(t), len(STOPS) - 2)
    f = t - i
    a, b = STOPS[i], STOPS[i + 1]
    return tuple(round(a[k] + (b[k] - a[k]) * f) for k in range(3))


def cell_color(r, c):
    return grad((r + c) / 12)


def draw_mosaic(img, x0, y0, pitch, tile, radius):
    d = ImageDraw.Draw(img, "RGBA")
    for r, row in enumerate(G):
        for c, ch in enumerate(row):
            x = x0 + c * pitch
            y = y0 + r * pitch
            fill = cell_color(r, c) + (255,) if ch == "#" else FAINT
            d.rounded_rectangle([x, y, x + tile, y + tile], radius=radius, fill=fill)


def font(size, bold=True):
    names = ["segoeuib.ttf", "arialbd.ttf"] if bold else ["segoeui.ttf", "arial.ttf"]
    for name in names:
        path = os.path.join(os.environ.get("WINDIR", r"C:\Windows"), "Fonts", name)
        if os.path.exists(path):
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def icon(out):
    img = Image.new("RGB", (512, 512), BG)
    pitch, tile = 50, 44
    size = pitch * 6 + tile
    draw_mosaic(img, (512 - size) // 2, (512 - size) // 2, pitch, tile, 10)
    img.save(os.path.join(out, "play_icon_512.png"))


def feature(out):
    img = Image.new("RGB", (1024, 500), BG)
    pitch, tile = 50, 44
    draw_mosaic(img, 70, (500 - (pitch * 6 + tile)) // 2, pitch, tile, 10)
    d = ImageDraw.Draw(img)
    d.text((470, 120), "GridPix", font=font(104), fill=(255, 255, 255))
    d.text((476, 250), "Colourful nonogram puzzles", font=font(40, bold=False), fill=(230, 222, 255))
    d.text((476, 315), "Anime pack  \u2022  Daily puzzle  \u2022  No ads", font=font(30, bold=False), fill=(255, 201, 61))
    img.save(os.path.join(out, "feature_graphic_1024x500.png"))


def vector():
    """Adaptive-icon foreground: 108dp canvas, mosaic centred inside the 66dp safe zone."""
    pitch, tile, rad = 7.6, 6.8, 1.5
    size = pitch * 6 + tile
    x0 = y0 = (108 - size) / 2
    paths = []
    for r, row in enumerate(G):
        for c, ch in enumerate(row):
            x, y = x0 + c * pitch, y0 + r * pitch
            w = tile - 2 * rad
            d = (f"M{x + rad:.2f},{y:.2f} h{w:.2f} a{rad},{rad} 0 0 1 {rad},{rad} v{w:.2f} "
                 f"a{rad},{rad} 0 0 1 -{rad},{rad} h-{w:.2f} a{rad},{rad} 0 0 1 -{rad},-{rad} v-{w:.2f} "
                 f"a{rad},{rad} 0 0 1 {rad},-{rad} z")
            if ch == "#":
                color = "#FF%02X%02X%02X" % cell_color(r, c)
            else:
                color = "#1AFFFFFF"
            paths.append(f'    <path android:fillColor="{color}" android:pathData="{d}" />')
    xml = ('<?xml version="1.0" encoding="utf-8"?>\n'
           '<!-- Generated by tools/store_graphics.py: 7x7 pixel "G" mosaic, violet-to-gold gradient. -->\n'
           '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
           '    android:width="108dp"\n    android:height="108dp"\n'
           '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
           + "\n".join(paths) + "\n</vector>\n")
    with open(VECTOR_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(xml)


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "."
    os.makedirs(out, exist_ok=True)
    icon(out)
    feature(out)
    vector()
    print("wrote play_icon_512.png, feature_graphic_1024x500.png to", out, "and", os.path.normpath(VECTOR_OUT))


if __name__ == "__main__":
    main()
